version: '3.3'

networks:
  starrocks-net:
    driver: bridge
    external: true

services:
  fe-server:
    image: starrocks-fe 
    container_name: fe-server
    build:
      context: ./image/fe
      dockerfile: Dockerfile.fe
    volumes:
      - starrocks-fe:/opt/starrocks/fe
    ports:
      - 8030:8030
      - 9030:9030
    networks:
      - starrocks-net
  
  be-server:
    image: starrocks-be
    container_name: be-server
    build:
      context: ./image/be
      dockerfile: Dockerfile.be
    volumes:
      - starrocks-be:/opt/starrocks/be
    ports:
      - 8040:8040
      - 9060:9060
    networks:
      - starrocks-net
    depends_on:
      - fe-server

volumes:
  starrocks-fe:
    external: true
  starrocks-be:
    external: true